///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace AOI_CRM_Eddie.Module.Inspection
{
    public partial class AutoInspection
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void chkAutoInspection()
        {
        	try
        	{
	            repo.AOIGUIV2.Element11026.Click("126;18");
	            repo.AOIGUIV2.Button4.Click();
	            repo.Settings.Result.Click();
	            
	        	if (repo.Settings.ResultDebug.Checked == true)
	        	{
	        		repo.Settings.ResultDebug.Click();
	        		repo.Settings.ResultDebug.Click();
	        	}
	        	else
	        	{
	        		repo.Settings.ResultDebug.Click();
	        	}
	        	
	            repo.Settings.Apply.Click();
	            repo.AOIGUI1.Button확인.Click();
	            repo.AOIGUIV2.Element11026.Click("126;18");
	            repo.AOIGUIV2.Button3.Click();
	            Delay.Seconds(3);
	            
	            if (repo.AOIGUIV2.Text1262.TextValue != "Running (SIM LM)")
	            {
	            	repo.AOIGUIV2.Button3.Click();
	            }
	            
	            repo.AOIGUI.Element5004Info.WaitForExists(121212);
	            Delay.Seconds(3);
	            repo.AOIGUI.Element5004.Click("31;8");
            }
            catch (Exception e)
            {
            	Class.AOILog.LogWrite("Check Auto Inspection error");
        		Class.AOILog.LogWrite(e.ToString());
        		Validate.Fail();
            }
        }
    }
}
