///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace AOI_CRM_Eddie.Module.Inspection
{
    public partial class ManualInspection
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void chkManualInspection()
        {
        	try
        	{
        		/*repo.AOIGUIV2.Element11026.Click("855;16");
	            repo.AOIGUIV2.Text1640.Click();
	            repo.AOIGUIV2.Text1640.TextValue= strCompName;
	            repo.AOIGUIV2.Button.Click();*/
	            repo.AOIGUIV2.Button1.Click();
	            Delay.Seconds(3);
	            
	            if (repo.AOIGUIV2.Text1262.TextValue != "Running (SIM LM)")
	            {
	            	repo.AOIGUIV2.Button1.Click();
	            }
	            
	            repo.AOIGUI.Element5006Info.WaitForExists(13579);
	            Delay.Seconds(1);
	            repo.AOIGUI.Element5006.Click();
        	}
            catch (Exception e)
            {
            	Class.AOILog.LogWrite("Check Manual Inspection error");
        		Class.AOILog.LogWrite(e.ToString());
        		Validate.Fail();
            }
        }
    }
}
