///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;
using System.IO;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace AOI_CRM_Eddie.Module.TeachingFiducial
{
    public partial class TestFiducials
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

       public void chkFiducials()
        {
        	try
        	{
	            repo.AOIGUIV2.Element11026.Click("348;18");
	            repo.AOIGUIV2.Element11027.Click("460;582");
	            repo.AOIGUIV2.TestAll.Click();
	            Delay.Seconds(3);
	            
	            string strPath = Directory.GetCurrentDirectory().Replace(@"\Release", "").Replace(@"\Debug", "") + @"\ComparePicture\TestFiducials_chkGoodScore.bmp";
	            bool compareFidScore = Class.ImgProcess.loadBitMap(strPath, 1 , repo.AOIGUIV2.Text1684);
	        	if (compareFidScore == true)
	        	{
		            repo.AOIGUIV2.Element1.Click();
		            repo.AOIGUIV2.Element11026.Click("850;18");
	        	}
        	}
        	catch (Exception e)
        	{
        		Class.AOILog.LogWrite("Check Fiducial failed");
        		Class.AOILog.LogWrite(e.ToString());
        		Validate.Fail();
        	}
        }
    }
}
