///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace AOI_CRM_Eddie.Module.CRMCase
{
    public partial class CAS_14264_N0L2
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void chkHalcon()
        {
            try
        	{
            	//string strPt = "PopUpTurret";
        		//Set AOIConfig default
            	Class.SetAOIConfig.SetDefault();
            	
            	//Backup 'license' folder at Project\bin
            	Class.CopyDelete cf = new Class.CopyDelete();
        		cf.BackupFolder("license",@"C:\Program Files\MVTec\HALCON-9.0\");
            	
        		//Delete 'license' folder at root path
        		cf.DeleteFolder(@"C:\Program Files\MVTec\HALCON-9.0\license");
        		
            	//Open AOIGUI
            	if (AOI_CRM_EddieRepository.Instance.AOIGUIV2.SelfInfo.Exists())
        		{
        			Host.Current.KillApplication(AOI_CRM_EddieRepository.Instance.AOIGUIV2.Self);
        		}
            	
            	Class.RunAOIGUI.RunWinMCS();
            	
	        	if (AOI_CRM_EddieRepository.Instance.WinMCS.Button확인Info.Exists(5555))
	        	{
	        		AOI_CRM_EddieRepository.Instance.WinMCS.Button확인.Click();
	        	}
	        	
	        	Class.RunAOIGUI.RunAOI();
	        	Class.RunAOIGUI.PopupTurretRun();
	        	
	        	AOI_CRM_EddieRepository.Instance.AOGUILMLOGINDLG.SelfInfo.WaitForExists(66666);
	        	
	        	Class.RunAOIGUI.PopupTurretKill();
	        	
	        	//Log-in > load JOB
	        	AOI_CRM_EddieRepository.Instance.AOGUILMLOGINDLG.Text1004.TextValue="kyadmin";
	            AOI_CRM_EddieRepository.Instance.AOGUILMLOGINDLG.Text1005.TextValue="21077421!";
	            AOI_CRM_EddieRepository.Instance.AOGUILMLOGINDLG.Button.Click();
	            
	            if (repo.ErrorReport.SelfInfo.Exists(13579))
	            {
	            	repo.ErrorReport.CloseTheProgram.Click();
	            	
	            	cf.RestoreFolder("license",@"C:\Program Files\MVTec\HALCON-9.0\");
	            	
	            	Class.AOILog.LogWrite("CAS-14264-N0L2 failed. Crash happen instead of Notification.");
	            	Validate.Fail();
	            }
	            
	            else if (AOI_CRM_EddieRepository.Instance.AOIGUI1.Button확인Info.Exists(13579))
	            {
	            	AOI_CRM_EddieRepository.Instance.AOIGUI1.Button확인.Click();
	            }
	            
	            AOI_CRM_EddieRepository.Instance.AOIGUI.Text10251Info.WaitForExists(66666);
	            Delay.Seconds(2);
	            AOI_CRM_EddieRepository.Instance.AOIGUI.Self.Click("93;233");
	            AOI_CRM_EddieRepository.Instance.AOIGUI1.Text57029.TextValue="kohyoung7 1array";
	            AOI_CRM_EddieRepository.Instance.AOIGUI1.Search.Click();
	            AOI_CRM_EddieRepository.Instance.AOIGUI1.Element8103.Click("279;35");
	            AOI_CRM_EddieRepository.Instance.AOIGUI1.Element8103.Click("279;35");
	            AOI_CRM_EddieRepository.Instance.List1000.NotUse.Click();
	            AOI_CRM_EddieRepository.Instance.AOIGUI1.ButtonOK.Click();
            }
            catch (Exception e)
            {
            	Class.AOILog.LogWrite("CAS-14264-N0L2: Check License/ Halcon key failed.");
        		Class.AOILog.LogWrite(e.ToString());
        		Validate.Fail();
            }
        }
    }
}
