///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;
using System.IO;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace AOI_CRM_Eddie.Module.CRMCase
{
    public partial class CAS_08329_X8X3
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void chkUploadKYPCB()
        {
            try
            {
            	//Set AOIConfig default
            	Class.SetAOIConfig.SetDefault();
            	
            	//Open AOIGUI & load JOB
            	Class.RunAOIGUI.OpenAOILoadJOB();
            	
            	UploadKYPCB("KYE Testboard V8 - Golden.KYPcb");
            	Delay.Seconds(2);
            	
            	UploadKYPCB("M1 top.KYPcb");
            	Delay.Seconds(2);
            	
            	UploadKYPCB("PRD06910.KYPcb");
            	Delay.Seconds(2);
            	
            	//Close AOIGUI
	            Class.RunAOIGUI.CloseAOI();
            }
            catch (Exception e)
            {
            	Class.AOILog.LogWrite("CAS-08329-X8X3: Check failed");
        		Class.AOILog.LogWrite(e.ToString());
        		Validate.Fail();
            }
        }
        
        public static void UploadKYPCB(string strKYPCBName)
        {
        	try
            {
            	repo.AOIGUIV2.Button2.Click();
	            repo.AOIGUI.Self.Click("186;77");
	            
	            if (repo.AOIGUIV2.Text10251Info.Exists(3333) == false)
	            {
	            	Keyboard.PrepareFocus(repo.AOIGUIV2.Self);
            		Keyboard.Press(System.Windows.Forms.Keys.N | System.Windows.Forms.Keys.Control, 49, Keyboard.DefaultKeyPressTime, 1, true);
	            }
	            
	            repo.AOIGUIV2.Text10251.Click();
	            repo.AOIGUIV2.Text10251.TextValue= "Eddie_Automation_Test_CAS-08329-X8X3_" + strKYPCBName;
	            repo.AOIGUIV2.Element11027.Click("469;405");
	            
	            string strFilePath = Directory.GetCurrentDirectory().Replace(@"\Release", "").Replace(@"\Debug", "") + @"\TestFiles\" + strKYPCBName;
	            /*string strFilePath = @"...\TestFiles\";
            	DirectoryInfo di = new DirectoryInfo(strFilePath);
            	string orrPath = di.FullName + strKYPCBName;*/
            	repo.Form열기.Text1148.TextValue= strFilePath; //orrPath;
            	
	            repo.Form열기.열기O.Click();
	            
	            if (repo.AOIGUI1.예YInfo.Exists(3579))
	            {
	            	repo.AOIGUI1.예Y.Click();
	            }
	            
	            repo.ChooseBoardPartTable.ApplySelected.Click();
	            
	            if (repo.AOIGUI1.Button확인Info.Exists(11111))
	            {
	            	repo.AOIGUI1.Button확인.Click();
	            	Class.AOILog.LogWrite("CAS-08329-X8X3: " + strKYPCBName + "load failed");
	            }
	            else
	            {
	            	repo.PCBSettingsInfo.Cancel.Click();
	            }
            }
            catch (Exception e)
            {
            	Class.AOILog.LogWrite("CAS-08329-X8X3: " + strKYPCBName + "load failed");
        		Class.AOILog.LogWrite(e.ToString());
            }
        }
    }
}
