///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;
using System.IO;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;


namespace AOI_CRM_Eddie.Module.CRMCase
{

}
namespace AOI_CRM_Eddie.Module.CRMCase
{
    public partial class CAS_13526_R2N7
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void chkNoData()
        {
        	try
        	{
        		//Set AOIConfig default
            	Class.SetAOIConfig.SetDefault();
            	
            	//Open AOIGUI & load JOB
            	Class.RunAOIGUI.OpenAOILoadJOB();
            	
	            repo.AOIGUIV2.Button4.Click();
	            repo.Settings.Engineers.Click();
	            repo.Settings.Tree1000.Click("15;203");
	            repo.Settings.Debug.Click();
	            
	            if (repo.Settings.CompareComponentCountOnFOVAndResul.Checked)
	            {
	            	repo.Settings.CompareComponentCountOnFOVAndResul.Click();
	            	repo.Settings.CompareComponentCountOnFOVAndResul.Click();
	            }
	            else
	            {
	            	repo.Settings.CompareComponentCountOnFOVAndResul.Click();
	            }
	            
	            repo.Settings.Apply.Click();
	            repo.AOIGUI1.Button확인.Click();
	            
	            Class.AOIInsp.ManualInspHold("X2");
	            Delay.Seconds(1);
	            
	            string strPath = Directory.GetCurrentDirectory().Replace(@"\Release", "").Replace(@"\Debug", "") + @"\ComparePicture\NoData_ImageViewer.bmp";
	            bool compareDVImage = Class.ImgProcess.loadBitMap(strPath, 1 , repo.AOIGUI.ImageViewer);
	            if (compareDVImage == true)
	            {
	            	repo.AOIGUI.Element5006.Click();
	            	Class.AOILog.LogWrite("CAS-13526-R2N7: CRM is reproduced, BUG found!!!");
	            	Validate.Fail();
	            }
	            
	            repo.AOIGUI.Element5006.Click();
	            
	            repo.AOIGUIV2.Button4.Click();
	            repo.Settings.Engineers.Click();
	            repo.Settings.Tree1000.Click("15;203");
	            repo.Settings.Debug.Click();
	            
	            if (repo.Settings.CompareComponentCountOnFOVAndResul.Checked)
	            {
	            	repo.Settings.CompareComponentCountOnFOVAndResul.Click();
	            }
	            else
	            {
	            	repo.Settings.CompareComponentCountOnFOVAndResul.Click();
	            	repo.Settings.CompareComponentCountOnFOVAndResul.Click();
	            }
	            
	            repo.Settings.Apply.Click();
	            repo.AOIGUI1.Button확인.Click();
	            
	            //Close AOIGUI
	            Class.RunAOIGUI.CloseAOI();
            }
            catch (Exception e)
            {
            	Class.AOILog.LogWrite("CAS-13526-R2N7: 'Compare component count on FOV and Result' failed");
        		Class.AOILog.LogWrite(e.ToString());
        		Validate.Fail();
            }
        }
    }
}
