///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace AOI_CRM_Eddie.Module.CRMCase
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CAS_13526_R2N7 recording.
    /// </summary>
    [TestModule("947ac20e-efbd-418a-80ca-6d90f15d2d88", ModuleType.Recording, 1)]
    public partial class CAS_13526_R2N7 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::AOI_CRM_Eddie.AOI_CRM_EddieRepository repository.
        /// </summary>
        public static global::AOI_CRM_Eddie.AOI_CRM_EddieRepository repo = global::AOI_CRM_Eddie.AOI_CRM_EddieRepository.Instance;

        static CAS_13526_R2N7 instance = new CAS_13526_R2N7();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CAS_13526_R2N7()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CAS_13526_R2N7 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            chkNoData();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
