///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;
using System.IO;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace AOI_CRM_Eddie.Module.CRMCase
{
    public partial class CAS_06639_H9N0
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void chkShieldPresetting()
        {
            try
            {
            	//Set AOIConfig default
            	Class.SetAOIConfig.SetDefault();
            	
            	//Open AOIGUI & load JOB
            	Class.RunAOIGUI.OpenAOILoadJOB();
            	
            retryChangePkg:
            	repo.AOIGUIV2.Element11026.Click("859;18");
	            repo.AOIGUIV2.EditPackage.Click();
	            repo.AOIGUIV2.Text1640.Click();
	            Keyboard.PrepareFocus(repo.AOIGUIV2.Text1640);
	            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
	            repo.AOIGUIV2.Text1640.TextValue= "X2";
	            repo.AOIGUIV2.Button.Click();
	            Delay.Milliseconds(500);
	            
	            repo.AOIGUIV2.Text1025.Click();
	            repo.AOIGUI.Text1025.Click();
	            Keyboard.PrepareFocus(repo.AOIGUI.Text1025);
	            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
	            repo.AOIGUI.Text1025.TextValue= "shield";
	            repo.AOIGUI.Text1025.PressKeys("{Return}");
	            repo.AOIGUI.Self.Click("130;72");
	            repo.AOIGUIV2.Apply.Click();
	            
	            if (repo.AOIGUIV2.Text1025.TextValue == "SHIELD")
	            {
	            	
	            }
	            else
	            {
	            	goto retryChangePkg;
	            }
	            
	            repo.AOIGUIV2.InspectionCondition.Click();
	            repo.AOIGUIV2.Element200.Click("27;42");
	            repo.AOIGUIV2.Package.Click();
	            repo.AOIGUIV2.Apply1.Click();
	            
	            repo.AOIGUIV2.Element500.Click("350;50");
	            repo.AOIGUI.TwoTerminalChip.Click();
	            repo.AOIGUIV2.Element500.Click("350;70");
	            repo.AOIGUI.SearchTerminalEdgeOnly.Click();
	            repo.AOIGUIV2.Package.Click();
	            repo.AOIGUIV2.Apply1.Click();
	            
	            repo.AOIGUIV2.Button1.Click();
	            Delay.Seconds(3);
	            
	            if (repo.AOIGUIV2.Text1262.TextValue != "Running (SIM LM)")
	            {
	            	repo.AOIGUIV2.Button1.Click();
	            }
	            
	            repo.AOIGUI.Element5006Info.WaitForExists(22222);
	            string strPath = Directory.GetCurrentDirectory().Replace(@"\Release", "").Replace(@"\Debug", "") + @"\ComparePicture\CAS-06639-H9N0_ImageViewer.bmp";
	            bool compareDVImage = Class.ImgProcess.loadBitMap(strPath, 0.999999 , repo.AOIGUI.ImageViewer);
	            if (compareDVImage == true)
	            {
	            	repo.AOIGUI.Element5006.Click();
	            }
	            else
	            {
	            	repo.AOIGUI.Element5006.Click();
	            	Class.AOILog.LogWrite("CAS-06639-H9N0: CRM is reproduced, BUG found!!!");
	            	Validate.Fail();
	            }
	            
	            //Close AOIGUI
	            Class.RunAOIGUI.CloseAOI();
            }
            catch (Exception e)
            {
            	Class.AOILog.LogWrite("CAS-06639-H9N0: Check Shield - Body Presetting - Body location mode failed");
        		Class.AOILog.LogWrite(e.ToString());
        		Validate.Fail();
            }
        }
    }
}
