///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;
using System.IO;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace AOI_CRM_Eddie.Module.CRMCase
{
    public partial class CAS_10157_Z8J8
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void chkOCVRInfo()
        {
            try
            {
            	//Set AOIConfig default
            	Class.SetAOIConfig.SetDefault();
            	
            	//Open AOIGUI & load JOB
            	Class.RunAOIGUI.OpenAOILoadJOB();
            	
            	repo.AOIGUIV2.Element11026.Click("865;16");
            	repo.AOIGUIV2.InspectionCondition.Click();
	            
	            Keyboard.PrepareFocus(repo.AOIGUIV2.Text1640);
	            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
	            
	            repo.AOIGUIV2.Text1640.TextValue= "R169";
	            repo.AOIGUIV2.Button.Click();
	            
	            //Check OCVR inspection condition
	            repo.AOIGUIV2.Element200.Click("39;129");
	            
	            string strPath = Directory.GetCurrentDirectory().Replace(@"\Release", "").Replace(@"\Debug", "") + @"\ComparePicture\OCVR_Element500.bmp";
	            bool compareOCVRInspCond = Class.ImgProcess.loadBitMap(strPath, 1 , repo.AOIGUIV2.Element500);
	        	if (compareOCVRInspCond == true)
	        	{
		            repo.AOIGUIV2.Element200.Click("9;129");
	        	}
	            
	            repo.AOIGUIV2.Package.Click();
	            repo.AOIGUIV2.Apply1.Click();
	            
	            repo.AOIGUIV2.Element500.Click("336;48");
	            repo.AOIGUI.ListItemOCR.Click();
	            repo.AOIGUIV2.Element500.Click("343;108");
	            repo.AOIGUIV2.Self.EnsureVisible();
            	Keyboard.Press("E9LE");
            	
            	repo.AOIGUIV2.Package.Click();
	            repo.AOIGUIV2.Apply1.Click();
	            
	            //Manual Inspection > Check & select OCVR Image Plane
	            repo.AOIGUIV2.Button1.Click();
	            Delay.Seconds(3);
	            
	            if (repo.AOIGUIV2.Text1262.TextValue != "Running (SIM LM)")
	            {
	            	repo.AOIGUIV2.Button1.Click();
	            }
	            
	            repo.AOIGUI.Element5006Info.WaitForExists(22222);
	            
	            repo.AOIGUI.Element200.Click("39;129");
	            repo.AOIGUI.Element500.Click("264;148");
	            repo.FormOCVRImagePlaneSelectWindowR2.ButtonOKInfo.Exists(5555);
	            
	            /*bool compareOCVR40 = Class.ImgProcess.loadBitMap(@"...\ComparePicture\OCVR_ImgPlane_40(AUTO).bmp", 1, repo.FormOCVRImagePlaneSelectWindowR2.Element1039);
	            bool compareOCVR39 = Class.ImgProcess.loadBitMap(@"...\ComparePicture\OCVR_ImgPlane_39(B_All).bmp", 1, repo.FormOCVRImagePlaneSelectWindowR2.Element1038);
	            bool compareOCVR38 = Class.ImgProcess.loadBitMap(@"...\ComparePicture\OCVR_ImgPlane_38(G_All).bmp", 1, repo.FormOCVRImagePlaneSelectWindowR2.Element1037);
	            bool compareOCVR37 = Class.ImgProcess.loadBitMap(@"...\ComparePicture\OCVR_ImgPlane_37(R_All).bmp", 1, repo.FormOCVRImagePlaneSelectWindowR2.Element1036);
	        	if (compareOCVR40 != true)
	        	{*/
		            repo.FormOCVRImagePlaneSelectWindowR2.Element1039.Click();
	        	/*}
	        	else if (compareOCVR39 != true)
	        	{*/
	        		repo.FormOCVRImagePlaneSelectWindowR2.Element1038.Click();
	        	/*}
	            else if (compareOCVR38 != true)
	        	{*/
	        		repo.FormOCVRImagePlaneSelectWindowR2.Element1037.Click();
	        	/*}
	            else if (compareOCVR37 != true)
	        	{*/
	        		repo.FormOCVRImagePlaneSelectWindowR2.Element1036.Click();
	        	/*}
	            else
	            {
	            	Class.AOILog.LogWrite("CAS-10157-Z8J8: There's no OCVR Image Plane available");
	            	Validate.Fail();
	            }*/
	            repo.FormOCVRImagePlaneSelectWindowR2.ButtonOK.Click();
	            
	            //Re-inspection & check the OCVR result
	            repo.AOIGUI.Element5001.Click();
	            repo.AOIGUI2.InspectComponentF3.Click();
	            repo.AOIGUI.Element5006Info.WaitForExists(22222);
	            repo.AOIGUI.Element200.Click("39;129");
	            Delay.Seconds(3);
	            repo.AOIGUI.Element5006.Click();
	            
	            //Close AOIGUI
	            Class.RunAOIGUI.CloseAOI();
            }
            catch (Exception e)
            {
            	Class.AOILog.LogWrite("CAS-10157-Z8J8: Check OCVR failed");
        		Class.AOILog.LogWrite(e.ToString());
        		Validate.Fail();
            }
        }
        
        //Using for cut the sample test purpose only
        public static void cropOCVRImgPlane()
        {
        	Class.ImgProcess.capAndCropRGB(repo.FormOCVRImagePlaneSelectWindowR2.Element1036,"OCVR_ImgPlane_37(R_All)",0,86,2,4,@"...\ComparePicture");
        	Class.ImgProcess.capAndCropRGB(repo.FormOCVRImagePlaneSelectWindowR2.Element1037,"OCVR_ImgPlane_38(G_All)",0,86,2,4,@"...\ComparePicture");
        	Class.ImgProcess.capAndCropRGB(repo.FormOCVRImagePlaneSelectWindowR2.Element1038,"OCVR_ImgPlane_39(B_All)",0,86,2,4,@"...\ComparePicture");
        	Class.ImgProcess.capAndCropRGB(repo.FormOCVRImagePlaneSelectWindowR2.Element1039,"OCVR_ImgPlane_40(AUTO)",0,86,2,4,@"...\ComparePicture");
        }
    }
}
