///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace AOI_CRM_Eddie.Module.CRMCase
{
    public partial class CAS_11742_F5C5
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void chkSaveDBTime()
        {
            try
            {
            	//Set AOIConfig default
            	Class.SetAOIConfig.SetDefault();
	            
            	//Open AOIGUI & Load JOB
            	Class.RunAOIGUI.OpenAOILoadJOB();
            	
            	//Check Manual inspection to prevent Auto inspection fail
            	Class.AOIInsp.ManualInsp("C454");
            	
            	//Check Auto inspection
	            Class.AOIInsp.AutoInspHold();
	            repo.AOIGUI.Element5005.Click();
	            repo.AOIGUI.Element5005Info.WaitForNotExists(3333);
	            
	            //Check "Saving result is in progress" time
	            repo.AOIGUI.ProgressBar1967Info.WaitForExists(6666);
	            repo.AOIGUI.ProgressBar1967Info.WaitForNotExists(33333);
	            bool check = repo.AOIGUI.ProgressBar1967Info.Exists();
	            
	            if (check == true)
	            {
	            	Class.AOILog.LogWrite("CAS-11742-F5C5: 'Saving result is in progress' status appear more than 33.3s (normal: under 30s), CRM failed");
	        		Validate.Fail();
	            }
	            
	            //stop > check status > reset > check status
	            repo.AOIGUIV2.Button6.Click();
	            Delay.Seconds(3);
	            
	            if (repo.AOIGUIV2.Text1262.TextValue == "Stop (SIM LM)")
	            {
	            	repo.AOIGUIV2.Button7.Click();
	            	Delay.Seconds(3);
	            }
	            
	            if (repo.AOIGUIV2.Text1262.TextValue == "Idle (SIM LM)")
	            {
	            	//Close AOIGUI
	            	Class.RunAOIGUI.CloseAOI();
	            }
            }
            catch (Exception e)
            {
            	Class.AOILog.LogWrite("CAS-11742-F5C5: Check failed");
        		Class.AOILog.LogWrite(e.ToString());
        		Validate.Fail();
            }
        }
    }
}
