///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;
using System.IO;
using System.Runtime.InteropServices;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace AOI_CRM_Eddie.Module.CRMCase
{
    public partial class CAS_09888_T6V3
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        [DllImport("kernel32")]
        public static extern long WritePrivateProfileString(string section, string key, string val, string strFilePath);
        
        public void chkResult()
        {
            try
            {
            	//Set AOIConfig default
            	Class.SetAOIConfig.SetDefault();
            	
            	Class.CopyDelete cf = new Class.CopyDelete();
            	cf.BackupFile("AoiGuiSetup.ini");
            	
            	string strIniPath = @"C:\Kohyoung\AOI\AOIGUISetup.ini";
	            WritePrivateProfileString("VISION", "2DThreshold", "20", strIniPath);
	            WritePrivateProfileString("VISION", "3DThreshold", "20", strIniPath);
	            WritePrivateProfileString("BARCODE", "Type", "5", strIniPath);
	            
	            //Open AOIGUI & Load JOB
	            Module.OpenCloseAOIGUI.OpenAOILoadJOB.Start();
	            
	            //Check Cambarcode found
	            repo.AOIGUIV2.Element11026.Click("362;18");
	            repo.AOIGUIV2.Element11027.Click("1119;29");
	            repo.PCBSettingsInfo.ComboBox2094.Click();
	            repo.List1000.ListItemCam.Click();
	            repo.PCBSettingsInfo.Apply.Click();
	            repo.AOIGUIV2.Element11026.Click("362;16");
	            repo.AOIGUIV2.Element11027.Click("469;669");
	            repo.AOIGUIV2.TestAll1.Click();
	            Delay.Seconds(2);
	            
	            if (repo.AOIGUIV2.Text1961.TextValue != "Found")
	            {
		            Class.AOILog.LogWrite("CAS-09888-T6V3: Teaching Barcode not found");
	            }
	            repo.AOIGUIV2.Element1.Click();
	            
	            //Check Manual inspection
	            string strPath = Directory.GetCurrentDirectory().Replace(@"\Release", "").Replace(@"\Debug", "") + @"\ComparePicture\CAS-09888-T6V3_ImageViewer.bmp";
	            
	            Class.AOIInsp.ManualInspHold("C454");
	            bool compareMImg = Class.ImgProcess.loadBitMap(strPath, 1, repo.AOIGUI.ImageViewer);
	        	if (compareMImg == true)
	        	{
		            repo.AOIGUI.Element5006.Click();
	        	}
	        	else
	        	{
		            Class.AOILog.LogWrite("CAS-09888-T6V3: Manual Inspection- Check Compare Defect Image failed");
	        		Validate.Fail();
	        	}
	        	
	            //Check Auto inspection
	            Class.AOIInsp.AutoInspHold();
	            repo.AOIGUI.C454.Click();
	            bool compareAImg = Class.ImgProcess.loadBitMap(strPath, 1, repo.AOIGUI.ImageViewer);
	        	if (compareAImg == true)
	        	{
		            repo.AOIGUI.Element5004.Click();
	        	}
	        	else
	        	{
		            Class.AOILog.LogWrite("CAS-09888-T6V3: Auto Inspection- Check Compare Defect Image failed");
	        		Validate.Fail();
	        	}
	            
	            cf.RestoreFile("AoiGuiSetup.ini");
	            
	            Class.RunAOIGUI.CloseAOI();
            }
            catch (Exception e)
            {
            	Class.AOILog.LogWrite("CAS-09888-T6V3: Check failed");
        		Class.AOILog.LogWrite(e.ToString());
        		Validate.Fail();
            }
        }
    }
}
