///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;
using System.IO;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace AOI_CRM_Eddie.Module.CRMCase
{
    public partial class CAS_08425_D1S1
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void chkKAP()
        {
            try
        	{
        		//Set AOIConfig default
            	Class.SetAOIConfig.SetDefault();
            	
            	//Open AOIGUI & load JOB
            	Class.RunAOIGUI.OpenAOILoadJOB();
            	
	            //Setting KAP
	            chkOnKAP();
	            
	            int iRECHK = 5;
	            
	            for (int i = 0; i < iRECHK; i++)
	            {
	            	//Unuse all component
		            Class.UnuseReuseDelete ur = new Class.UnuseReuseDelete();
		            ur.UnuseComponents();
		            
		            //Reuse component
		            ur.ReuseComponents("x2");
		        	ur.ReuseComponents("r510");
		        	ur.ReuseComponents("C379");
		        	
		        	//Delete package
		        	ur.DeletePkg("x2");
		        	ur.DeletePkg("r510");
		        	ur.DeletePkg("C379");
		            
		            //Perform KAP
		            chkPerformKAP();
		            
		            //Reload JOB
		            repo.AOIGUIV2.Button2.Click();
		            repo.AOIGUI.Self.Click("116;116");
		            repo.AOIGUI.Self.Click("411;979");
		            
		            if (repo.AOIGUI1.SelfInfo.Exists(3333))
		            {
		            	repo.AOIGUI1.아니요N.Click();
		            }
		            
		            repo.AOIGUI1.Text57029.TextValue="kohyoung7 1array";
		            repo.AOIGUI1.Search.Click();
		            repo.AOIGUI1.Element8103.Click("279;35");
		            repo.AOIGUI1.Element8103.Click("279;35");
		            Delay.Milliseconds(333);
		            repo.List1000.NotUse.Click();
		            repo.AOIGUI1.ButtonOK.Click();
		            
		            repo.PCBSettingsInfo.CancelInfo.WaitForExists(33333);
		            Delay.Seconds(2);
		        	if (repo.AOIGUI1.Element201Info.Exists(3333))
		        	{
		        		repo.AOIGUI1.Element201.Click();
		        		repo.PCBSettingsInfo.Cancel.Click();
		        	}
		        	else
		        	{
		        		repo.PCBSettingsInfo.Cancel.Click();
		        	}
	            }
	        	
	            //Close AOIGUI
	            Class.RunAOIGUI.CloseAOI();
            }
            catch (Exception e)
            {
            	Class.AOILog.LogWrite("CAS-08425-D1S1: Check KAP failed");
        		Class.AOILog.LogWrite(e.ToString());
        		Validate.Fail();
            }
        }
        
        public void chkOnKAP()
        {
        	try
        	{
	            repo.AOIGUIV2.Button4.Click();
	            repo.Settings.KSMART.Click();
	            repo.Settings.TreeItemKAP.Click();
	            
	        	if (repo.Settings.UseKAPKohYoungAutoProgramming.Checked == true)
	        	{
	        		repo.Settings.UseKAPKohYoungAutoProgramming.Click();
	        		repo.Settings.UseKAPKohYoungAutoProgramming.Click();
	        	}
	        	else
	        	{
	        		repo.Settings.UseKAPKohYoungAutoProgramming.Click();
	        	}
	        	
	        	repo.Settings.Apply.Click();
	        	repo.AOIGUI1.Button확인.Click();
        	}
            catch (Exception e)
            {
            	Class.AOILog.LogWrite("AOI Settings- Turn On KAP function error");
        		Class.AOILog.LogWrite(e.ToString());
        		Validate.Fail();
            }
        }
        
        public void chkPerformKAP()
        {
        	try
        	{
        	retryKAP:
	            AOI_CRM_EddieRepository.Instance.AOIGUIV2.Element11026.Click("610;18");
	            Delay.Milliseconds(100);
	            
	            if (AOI_CRM_EddieRepository.Instance.AOIGUIV2.Element49001Info.Exists())
	            {
	            	AOI_CRM_EddieRepository.Instance.AOIGUIV2.Element1027.Click("386;15");
		            Delay.Milliseconds(100);
		            AOI_CRM_EddieRepository.Instance.AOIGUI.Self.Click("164;47");
		            Delay.Milliseconds(100);
	            }
	            
	            AOI_CRM_EddieRepository.Instance.AOIGUIV2.Element11026.Click("610;18");
	            Delay.Milliseconds(100);
	            
	            if (AOI_CRM_EddieRepository.Instance.AOIGUIV2.Element49001Info.Exists())
	            {
	            	AOI_CRM_EddieRepository.Instance.AOIGUIV2.Element49001.Click("360;125");
	            	Delay.Milliseconds(100);
	            }
	            
	            string strPath = Directory.GetCurrentDirectory().Replace(@"\Release", "").Replace(@"\Debug", "") + @"\ComparePicture\PerformKAP_CheckKAPLib.bmp";
	            bool compareKAPLib = Class.ImgProcess.loadBitMap(strPath, 1, AOI_CRM_EddieRepository.Instance.AOIGUI.Self);
	        	if (compareKAPLib == true)
	        	{
		            AOI_CRM_EddieRepository.Instance.AOIGUI.Self.Click("179;15");
		            AOI_CRM_EddieRepository.Instance.AOIGUIV2.Element11026.Click("610;18");
	        	}
	        	else
	        	{
		            AOI_CRM_EddieRepository.Instance.AOIGUI.Self.Click("179;15");
		            Delay.Milliseconds(100);
		            AOI_CRM_EddieRepository.Instance.AOIGUI.Self.Click("179;15");
		            AOI_CRM_EddieRepository.Instance.AOIGUIV2.Element11026.Click("610;18");
	        	}
	        	
	            AOI_CRM_EddieRepository.Instance.AOIGUIV2.Element49001.Click("636;166");
	            Delay.Milliseconds(100);
	            
	            if (repo.Warning.SelfInfo.Exists(3333))
	            {
	            	repo.Warning.Button확인.Click();
	            	CreateKAPLib();
	            	goto retryKAP;
	            }
	            
	            AOI_CRM_EddieRepository.Instance.AOIGUIV2.Element56039Info.WaitForExists(999999);
	            AOI_CRM_EddieRepository.Instance.AOIGUIV2.Element56039.Click();
        	}
            catch (Exception e)
            {
            	Class.AOILog.LogWrite("Perform KAP error");
        		Class.AOILog.LogWrite(e.ToString());
        		Validate.Fail();
            }
        }
        
        //For crop the test sample purpose only 
        public static void cropKAPLibImg()
        {
        	string strPath = Directory.GetCurrentDirectory().Replace(@"\Release", "").Replace(@"\Debug", "") + @"\ComparePicture";
        	Class.ImgProcess.capAndCropRGB(repo.AOIGUI.Self,"PerformKAP_CheckKAPLib",0,0,8,7,strPath);
        }
        
        //Create KAP Lib at KSMART server
        public static void CreateKAPLib()
        {
        	Host.Current.OpenBrowser("http://10.1.10.41/auth/login", "Chrome", "", false, true, false, false, false, false, false, true);
        	
        	repo.KSMART.Http1011041AuthLogin.TextInfo.Exists();
        	repo.KSMART.Http1011041AuthLogin.Text.PressKeys("kyadmin");
            repo.KSMART.Http1011041AuthLogin.Password.PressKeys("21077421!");
            repo.KSMART.Http1011041AuthLogin.BtnBtnLgFontSize18px.Click();
            Delay.Milliseconds(222);
            repo.KSMART.Cancel.Click();
            Delay.Milliseconds(222);
            
            repo.KSMART.Library.Click();
            Delay.Milliseconds(222);
            repo.KSMART.KAPLibraryManager.Click();
            Delay.Milliseconds(222);
            
            repo.KSMART.ButtonTagGroupSettings.Click();
            Delay.Milliseconds(222);
            repo.KSMART.ModalDialogModalDialogCentered.ButtonTagAddLibrary.Click();
            Delay.Milliseconds(222);
            repo.KSMART.ModalDialogModalDialogCentered.MatRadioOuterCircle.Click();
            Delay.Milliseconds(222);
            repo.KSMART.ModalDialogModalDialogCentered.ButtonTagOK.Click();
            Delay.Seconds(1);
            
            repo.KSMART.Self.EnsureVisible();
            Keyboard.Press("Eddie_AOI Automation KAP Test");
            repo.KSMART.ButtonTagCancel.Click();
            Delay.Milliseconds(222);
            
            Host.Current.KillApplication(AOI_CRM_EddieRepository.Instance.KSMARTGoogleChrome.Self);
            
            repo.AOIGUIV2.Self.Click();
            repo.AOIGUIV2.Element11026.Click("607;15");
            repo.AOIGUIV2.Element1026.Click();
        }
    }
}
