///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;
using System.IO;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace AOI_CRM_Eddie.Module.CRMCase
{
    public partial class CAS_11804_X1D6
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void chkPolImgPlane()
        {
            try
            {
            	//Set AOIConfig default
            	Class.SetAOIConfig.SetDefault();
            	
            	//Open AOIGUI & load JOB
            	Class.RunAOIGUI.OpenAOILoadJOB();
            	
            	repo.AOIGUIV2.Element11026.Click("865;16");
            	repo.AOIGUIV2.InspectionCondition.Click();
	            
	            Keyboard.PrepareFocus(repo.AOIGUIV2.Text1640);
	            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
	            
	            repo.AOIGUIV2.Text1640.TextValue= "D68";
	            repo.AOIGUIV2.Button.Click();
	            
	            //Check Polarity inspection condition
	            repo.AOIGUIV2.Element200.Click("39;182");
	            
	            string strPath = Directory.GetCurrentDirectory().Replace(@"\Release", "").Replace(@"\Debug", "") + @"\ComparePicture\Polarity_Element500.bmp";
	            bool comparePLInspCond = Class.ImgProcess.loadBitMap(strPath, 1 , repo.AOIGUIV2.Element500);
	        	if (comparePLInspCond == true)
	        	{
		            repo.AOIGUIV2.Element200.Click("9;182");
	        	}
	            
	            repo.AOIGUIV2.Package.Click();
	            repo.AOIGUIV2.Apply1.Click();
	            
	            //Manual Inspection > Check & select Polarity Image Plane
	            repo.AOIGUIV2.Button1.Click();
	            Delay.Seconds(3);
	            
	            if (repo.AOIGUIV2.Text1262.TextValue != "Running (SIM LM)")
	            {
	            	repo.AOIGUIV2.Button1.Click();
	            }
	            
	            repo.AOIGUI.Element5006Info.WaitForExists(22222);
	            
	            repo.AOIGUI.Element200.Click("39;182");
	            repo.AOIGUI.Element500.Click("339;169");
	            
	            if (repo.AOIGUI1.예YInfo.Exists(3333))
	            {
	            	repo.AOIGUI1.예Y.Click();
	            }
	            
	            string strPath2 = Directory.GetCurrentDirectory().Replace(@"\Release", "").Replace(@"\Debug", "") + @"\ComparePicture\Polarity_ImgPlane_ContainerHash32770.bmp";
	            bool comparePlImgPlane = Class.ImgProcess.loadBitMap(strPath2, 1 , repo.FormPolarityImagePlaneSelectWindow.ContainerHash32770);
	        	if (comparePlImgPlane == true)
	        	{
	        		Class.AOILog.LogWrite("CAS-11804-X1D6: Unable to check the Polarity Image Plane");
	        		Validate.Fail();
	        	}
	            
	            repo.FormPolarityImagePlaneSelectWindow.ButtonOKInfo.Exists(5555);
	            repo.FormPolarityImagePlaneSelectWindow.Element1039.Click();
	            
	            if (repo.AOIGUI1.예YInfo.Exists(3333))
	            {
	            	repo.AOIGUI1.예Y.Click();
	            }
	            else if (repo.FormPolarityImagePlaneSelectWindow.ButtonOKInfo.Exists(5555))
	            {
	            	repo.FormPolarityImagePlaneSelectWindow.ButtonOK.Click();
	            }
	            
	            //Re-inspection & check the Polarity result
	            repo.AOIGUI.Element5001.Click();
	            repo.AOIGUI2.InspectComponentF3.Click();
	            repo.AOIGUI.Element5006Info.WaitForExists(22222);
	            repo.AOIGUI.Element200.Click("39;182");
	            Delay.Seconds(3);
	            repo.AOIGUI.Element5006.Click();
	            
	            //Close AOIGUI
	            Class.RunAOIGUI.CloseAOI();
            }
            catch (Exception e)
            {
            	Class.AOILog.LogWrite("CAS-11804-X1D6: Check Polarity Image Plane for 'Light component' failed");
        		Class.AOILog.LogWrite(e.ToString());
        		Validate.Fail();
            }
        }
    }
}
