///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;
using System.Windows.Forms;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace AOI_CRM_Eddie.Module.CRMCase
{
    public partial class CAS_12307_S0N3
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void chkBGAOffset()
        {
            try
            {
            	//Set AOIConfig default
            	Class.SetAOIConfig.SetDefault();
            	
            	//Open AOIGUI & load JOB
            	Class.RunAOIGUI.OpenAOILoadJOB();
            	
            	repo.AOIGUIV2.Element11026.Click("856;20");
	            repo.AOIGUIV2.EditPackage.Click();
	            repo.AOIGUIV2.Text1640.Click();
	            
	            Keyboard.PrepareFocus(repo.AOIGUIV2.Text1640);
	            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
	            repo.AOIGUIV2.Text1640.TextValue= "IC2";
	            
	            repo.AOIGUIV2.Button.Click();
	            repo.AOIGUIV2.Element269.Click("334;229");
	            repo.AOIGUIV2.Delete.Click();
	            repo.Delete.Package.Click();
	            repo.Delete.Delete.Click();
	            
	            repo.AOIGUIV2.Button.Click();
	            repo.CreateADefaultPackage.Element1025.Click();
	            repo.AOIGUI.Text1025.Click();
	            repo.AOIGUI.Text1025.TextValue= "bga";
	            repo.AOIGUI.Text1025.PressKeys("{Return}");
	            repo.AOIGUI.Self.Click("176;72");
	            repo.CreateADefaultPackage.Apply.Click();
	            Delay.Seconds(2);
	            
	            repo.AOIGUIV2.Element201.DoubleClick("360;36");	            
	            string strOffsetX = Class.ImgProcess.getPointText();
	            if (strOffsetX != "0")
	            {
	            	Class.AOILog.LogWrite("CAS-12307-S0N3: Check Body Offset X of BGA failed (must be '0' instead");
	        		Validate.Fail();
	            }
	            
	            repo.AOIGUIV2.Element201.DoubleClick("410;36");
	            string strOffsetY = Class.ImgProcess.getPointText();
	            if (strOffsetY != "0")
	            {
	            	Class.AOILog.LogWrite("CAS-12307-S0N3: Check Body Offset Y of BGA failed (must be '0' instead");
	        		Validate.Fail();
	            }
	            
	            repo.AOIGUIV2.Button1.Click();
	            Delay.Seconds(3);
	            
	            if (repo.AOIGUIV2.Text1262.TextValue != "Running (SIM LM)")
	            {
	            	repo.AOIGUIV2.Button1.Click();
	            }
	            
	            repo.AOIGUI.Element5006Info.WaitForExists(22222);
	            repo.AOIGUI.Element5006.Click();
	            
	            //Close AOIGUI
	            Class.RunAOIGUI.CloseAOI();
            }
            catch (Exception e)
            {
            	Class.AOILog.LogWrite("CAS-12307-S0N3: Check Body Offset of BGA failed");
        		Class.AOILog.LogWrite(e.ToString());
        		Validate.Fail();
            }
        }
    }
}
