///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;
using System.Runtime.InteropServices;
using System.IO;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace AOI_CRM_Eddie.Module.CRMCase
{
    public partial class CAS_08503_N6H7
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        [DllImport("kernel32")]
        public static extern long WritePrivateProfileString(string section, string key, string val, string strFilePath);
        
        public void chkPassFid()
        {
            try
            {
            	//Set AOIConfig default
            	Class.SetAOIConfig.SetDefault();
            	
            	Class.CopyDelete cf = new Class.CopyDelete();
            	cf.BackupFile("AoiGuiSetup.ini");
            	
            	string strIniPath = @"C:\Kohyoung\AOI\AOIGUISetup.ini";
	            WritePrivateProfileString("InspSeq", "PassWhenFidFail", "1", strIniPath);
	            
	            Module.OpenCloseAOIGUI.OpenAOILoadJOB.Start();
	            
	            //Check Fiducial not found
	            repo.AOIGUIV2.Element11026.Click("348;18");
	            repo.AOIGUIV2.Element11027.Click("460;582");
	            
	            Keyboard.PrepareFocus(repo.AOIGUIV2.Fiducial.Text1357);
            	Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            	repo.AOIGUIV2.Fiducial.Text1357.TextValue= "100";
            	
            	repo.AOIGUIV2.Fiducial.AllFiducials.Click();
            	repo.AOIGUIV2.Fiducial.Apply2.Click();
	            
	            repo.AOIGUIV2.TestAll.Click();
	            Delay.Seconds(3);
	            
	            string strPath = Directory.GetCurrentDirectory().Replace(@"\Release", "").Replace(@"\Debug", "") + @"\ComparePicture\TestFiducials_chkBadScore.bmp";
	            bool compareFidScore = Class.ImgProcess.loadBitMap(strPath, 1 , repo.AOIGUIV2.Text1684);
	        	if (compareFidScore == true)
	        	{
		            repo.AOIGUIV2.Element1.Click();
		            repo.AOIGUIV2.Element11026.Click("850;18");
	        	}
	        	
	            //Check Auto inspection
	            repo.AOIGUIV2.Element11026.Click("126;18");
	            repo.AOIGUIV2.Button3.Click();
	            Delay.Seconds(3);
	            
	            if (repo.AOIGUIV2.Text1262.TextValue != "Running (SIM LM)")
	            {
	            	repo.AOIGUIV2.Button3.Click();
	            }
	            
	            if (repo.AOIGUI.ButtonPassBoardFiducialFaiInfo.Exists() == false)
	            {
	            	Class.AOILog.LogWrite("CAS-08503-N6H7: Check Pass Board (Fiducial Fail) not found");
	            	Validate.Fail();
	            }
	            
	            repo.AOIGUIV2.Button6.Click();
	            repo.AOIGUIV2.Button7.Click();
	            
	            cf.RestoreFile("AoiGuiSetup.ini");
	            
	            //Close AOIGUI
	            Class.RunAOIGUI.CloseAOI();
            }
            catch (Exception e)
            {
            	Class.AOILog.LogWrite("CAS-08503-N6H7: Check failed");
        		Class.AOILog.LogWrite(e.ToString());
        		Validate.Fail();
            }
        }
    }
}
