///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;
using System.IO;
using System.Collections;


using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;






namespace AOI_CRM_Eddie.Module.CRMCase
{

}
namespace AOI_CRM_Eddie.Module.CRMCase
{

}
namespace AOI_CRM_Eddie.Module.CRMCase
{

}
namespace AOI_CRM_Eddie.Module.CRMCase
{

}
namespace AOI_CRM_Eddie.Module.CRMCase
{

}
namespace AOI_CRM_Eddie.Module.CRMCase
{
    public partial class Recording1
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void test()
        {
        	Host.Current.OpenBrowser("http://10.1.10.41/auth/login", "Chrome", "", true, true, false, false, false, false, false, true);
        	
        	repo.KSMART.Http1011041AuthLogin.TextInfo.Exists();
        	repo.KSMART.Http1011041AuthLogin.Text.PressKeys("kyadmin");
            repo.KSMART.Http1011041AuthLogin.Password.PressKeys("21077421!");
            repo.KSMART.Http1011041AuthLogin.BtnBtnLgFontSize18px.Click();
            Delay.Milliseconds(222);
            repo.KSMART.Cancel.Click();
            Delay.Milliseconds(222);
            
            repo.KSMART.Library.Click();
            Delay.Milliseconds(222);
            repo.KSMART.KAPLibraryManager.Click();
            Delay.Milliseconds(222);
            
            repo.KSMART.ButtonTagGroupSettings.Click();
            Delay.Milliseconds(222);
            repo.KSMART.ModalDialogModalDialogCentered.ButtonTagAddLibrary.Click();
            Delay.Milliseconds(222);
            repo.KSMART.ModalDialogModalDialogCentered.MatRadioOuterCircle.Click();
            Delay.Milliseconds(222);
            repo.KSMART.ModalDialogModalDialogCentered.ButtonTagOK.Click();
            Delay.Seconds(1);
            
            repo.KSMART.Self.EnsureVisible();
            Keyboard.Press("Eddie_AOI Automation KAP Test");
            repo.KSMART.ButtonTagCancel.Click();
            Delay.Milliseconds(222);
            
            Host.Current.KillApplication(AOI_CRM_EddieRepository.Instance.KSMARTGoogleChrome.Self);
            
            repo.AOIGUIV2.Self.Click();
            repo.AOIGUIV2.Element11026.Click("607;15");
            repo.AOIGUIV2.Element1026.Click();
        }
    }
}
