///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace AOI_CRM_Eddie.Module.UnuseReuse
{
    public partial class UnuseComponents
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void chkUnuseComponents()
        {
        	try
        	{
	            repo.AOIGUIV2.Element11026.Click("850;18");
	            repo.AOIGUIV2.ComboBox1873.Click("97;11");
	            repo.List1000.Unuse.Click("33;9");
	            repo.AOIGUIV2.Element269.Click("333;222");
	            Delay.Milliseconds(200);
	            
	            Mouse.ScrollWheel(3600);
	            Delay.Milliseconds(500);
	           
	            Mouse.ScrollWheel(3600);
	            Delay.Milliseconds(500);
	            
	            Mouse.ScrollWheel(3600);
	            Delay.Milliseconds(500);
	            
	            Mouse.ScrollWheel(3600);
	            Delay.Milliseconds(500);
	            
	            Mouse.ScrollWheel(3600);
	            Delay.Milliseconds(500);
	            
	            Mouse.ScrollWheel(3600);
	            Delay.Milliseconds(500);
	            
	            mouseDragUnuse();
	            Delay.Milliseconds(0);
	            
	            //repo.AOIGUIV2.AOIGUI.Element269.MoveTo("50;45");
	            //Delay.Milliseconds(200);
	            //Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
	            //Delay.Milliseconds(200);
	            
	            //repo.AOIGUIV2.AOIGUI.Element269.MoveTo("626;436");
	            //Delay.Milliseconds(200);
	            //Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
	            //Delay.Milliseconds(200);
        	}
            catch (Exception e)
            {
            	Class.AOILog.LogWrite("Unuse Components error");
        		Class.AOILog.LogWrite(e.ToString());
        		Validate.Fail();
            }
        }
        
        public void mouseDragUnuse()
        {
        	//Trong bat ky truong hop, su dung toa do cua Element lam dich den (MoveTo > ButtonUp) deu se khong hoat dong
        	
        	repo.AOIGUIV2.Element269.Click("50;45");
        	//Mouse.Click(64,210);
        	Delay.Milliseconds(500);
        	Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
        	Delay.Milliseconds(500);
        	
        	//repo.AOIGUIV2.AOIGUI.Element269.MoveTo("626;436");
        	Mouse.MoveTo(1266,616);
        	Delay.Milliseconds(500);
        	Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
        	Delay.Milliseconds(500);
        }
    }
}
