///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace AOI_CRM_Eddie.Module.OpenCloseAOIGUI
{
    public partial class CloseAOI
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void chkCloseAOI()
        {
        	try
        	{
        		Delay.Seconds(3);
	        	repo.AOIGUIV2.Button5.Click();
	        		        	
	        	if (repo.AOIGUI1.예YInfo.Exists(3333))
	        	{
	        		repo.AOIGUI1.예Y.Click();
	        	}
	        	else
	        	{
	        		repo.AOIGUIV2.Button5.Click();
	        		repo.AOIGUI1.예Y.Click();
	        	}
	        	if (repo.AOIGUI1.아니요NInfo.Exists(5555))
	        	{
	        		repo.AOIGUI1.아니요N.Click();
	        	}
	        	Delay.Seconds(3);
        	}
            catch (Exception e)
            {
            	Class.AOILog.LogWrite("Close AOIGUI error");
        		Class.AOILog.LogWrite(e.ToString());
        		Validate.Fail();
            }
        }
    }
}
