///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;
using System.Data;
using System.Diagnostics;
using System.IO;
using System.Runtime.InteropServices;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace AOI_CRM_Eddie.Module.OpenCloseAOIGUI
{
    public partial class OpenAOILoadJOB
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        string pT = "PopUpTurret";
        
        public void openNLoadJOB()
        {
        	try
        	{
        		if (repo.AOIGUIV2.SelfInfo.Exists())
        		{
        			Host.Current.KillApplication(repo.AOIGUIV2.Self);
        		}
	        	
        		Class.RunAOIGUI.RunWinMCS();
	        	
	        	if (repo.WinMCS.Button확인Info.Exists(5555))
	        	{
	        		repo.WinMCS.Button확인.Click();
	        	}
	        	
	        	Class.RunAOIGUI.RunAOI();
	        	PopupTurretRun();
	        	
	        	repo.AOGUILMLOGINDLG.SelfInfo.WaitForExists(66666);
	        	
	        	PopupTurretKill();
	        	LogInLoadJOB();
	        	chkCTCpopup();
	        	Delay.Seconds(2);
        	}
        	catch (Exception e)
            {
            	Class.AOILog.LogWrite("Open AOIGUI & Load JOB error");
        		Class.AOILog.LogWrite(e.ToString());
        		Validate.Fail();
            }
        }
        
        private void PopupTurretRun()
        {
            Process[] prList = Process.GetProcessesByName(pT);
            if (prList.Length < 1)
            {
                Process.Start(pT + ".exe");
            }
        }
        
        private void PopupTurretKill()
        {
            Process[] prList = Process.GetProcessesByName(pT);
			foreach (Process item in prList)
			{
				item.Kill();
			}
        }
        
        public static void LogInLoadJOB()
        {
            repo.AOGUILMLOGINDLG.Text1004.TextValue="kyadmin";
            repo.AOGUILMLOGINDLG.Text1005.TextValue="21077421!";
            repo.AOGUILMLOGINDLG.Button.Click();
            
            if (repo.AOIGUI1.Button확인Info.Exists(13579))
            {
            	repo.AOIGUI1.Button확인.Click();
            }
            
            repo.AOIGUI.Text10251Info.WaitForExists(66666);
            Delay.Seconds(2);
            repo.AOIGUI.Self.Click("93;233");
            repo.AOIGUI1.Text57029.TextValue="kohyoung7 1array";
            repo.AOIGUI1.Search.Click();
            repo.AOIGUI1.Element8103.Click("279;35");
            repo.AOIGUI1.Element8103.Click("279;35");
            repo.List1000.NotUse.Click();
            repo.AOIGUI1.ButtonOK.Click();
        }
        
        public void chkCTCpopup()
        {
            repo.PCBSettingsInfo.CancelInfo.WaitForExists(33333);
            Delay.Seconds(2);
        	if (repo.AOIGUI1.Element201Info.Exists(3333))
        	{
        		repo.AOIGUI1.Element201.Click();
        		repo.PCBSettingsInfo.Cancel.Click();
        	}
        	else
        	{
        		repo.PCBSettingsInfo.Cancel.Click();
        	}
        }
    }
}
